-- Autogenerated: do not edit this file
IF OBJECT_ID('ledger_service.dbo.BATCH_STEP_EXECUTION_CONTEXT') IS NOT NULL
    DROP TABLE ledger_service.dbo.BATCH_STEP_EXECUTION_CONTEXT ;
    
IF OBJECT_ID('ledger_service.dbo.BATCH_JOB_EXECUTION_CONTEXT') IS NOT NULL
    DROP TABLE  ledger_service.dbo.BATCH_JOB_EXECUTION_CONTEXT ;
    
IF OBJECT_ID('ledger_service.dbo.BATCH_STEP_EXECUTION') IS NOT NULL
    DROP TABLE  ledger_service.dbo.BATCH_STEP_EXECUTION ;
    
IF OBJECT_ID('ledger_service.dbo.BATCH_JOB_EXECUTION_PARAMS') IS NOT NULL
    DROP TABLE  ledger_service.dbo.BATCH_JOB_EXECUTION_PARAMS ;
    
IF OBJECT_ID('ledger_service.dbo.BATCH_JOB_EXECUTION') IS NOT NULL
    DROP TABLE  ledger_service.dbo.BATCH_JOB_EXECUTION ;
    
IF OBJECT_ID('ledger_service.dbo.BATCH_JOB_INSTANCE') IS NOT NULL
    DROP TABLE  ledger_service.dbo.BATCH_JOB_INSTANCE ;
    
IF OBJECT_ID('ledger_service.dbo.BATCH_STEP_EXECUTION_SEQ') IS NOT NULL
    DROP TABLE  ledger_service.dbo.BATCH_STEP_EXECUTION_SEQ ;
    
IF OBJECT_ID('ledger_service.dbo.BATCH_JOB_EXECUTION_SEQ') IS NOT NULL
    DROP TABLE  ledger_service.dbo.BATCH_JOB_EXECUTION_SEQ ;
    
IF OBJECT_ID('ledger_service.dbo.BATCH_JOB_SEQ') IS NOT NULL
    DROP TABLE  ledger_service.dbo.BATCH_JOB_SEQ ;
